### ISSUE TITLE
今日の飯テロ

### ISSUE THREAD

**Issue by ThireFayde** [april-knights-dev/sharemusic_bot#8]
share_debzap に投稿されたご飯の写真を指定時間に投稿してくる

検討事項
・指定時間にどこに投稿するのか…？

要件定義
・29日に肉の画像を社長の部屋に投稿してほしい（焼肉のお店情報付きで）
・ご飯時に欲しい
・夜中に欲しい
・29日は肉だけ投稿してほしい
・カロリー表示
・製品情報
・うまめしと連携（飯テロした料理に基づいてお店が投稿される）
・26日にラーメン次郎の写真を投稿（ボブのお部屋と拓殖くんのお部屋に投稿）
・15日をイチゴの日としてスイーツとかの投稿をする
・botに向かって画像を投げたらdebzapに投稿してくれる

仕様決定
・

**Comment by kiddykazz** [comment]
仕様見直しの結果一旦不要となったのでクローズ
(メンダコの存在意義がぶれるので)
